### ISSUE TITLE
Make new release/webpage with ReleaseTools

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/radiroot#3]
* https://github.com/gap-system/ReleaseTools
* https://github.com/gap-system/GitHubPagesForGAP

**Comment by olexandr-konovalov** [comment]
After the release, remember to check the status of package tests in the new version when they are run with the `stable-4.9` branch of the GAP repository. Please see https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9-staging to inspect them: click on the line corresponding to this package and scroll till the very end of the log file to see the output of the package tests, the summary, and further instructions.

As soon as the package tests will run without diffs, they will be moved to https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9. This will be very helpful to monitor in the future that the package is still usable and that no changes in the GAP system break the package.

**Comment by fingolfin** [comment]
Note that the old package homepage is gone and won't be restored.

**Comment by fingolfin** [comment]
Update: the old homepage was restored now after all! I have access to it, and could turn it into a redirect if desired resp. necessary.

**Comment by olexandr-konovalov** [comment]
The old page now redirects to the new one.
